### PR TITLE
added support for headers on LongPollingTransport

### PR DESCRIPTION
**Pull request by couchand**

### CODE REVIEW

**Review by Amila17 — APPROVED** [review]

**Review by stewoe — APPROVED** [review]
Needed to work correctly with salesforcde streaming api and salesforce platform events.
Would be useful to add to the master branch and to the Nuget package

**Comment by guruprasad83** [comment]
@stewoe - any idea when this commit will be pushed to nuget package. Since am using addheaders and if it is  taking is there any alternative to add headers?

**Comment by kjkrum** [comment]
Doesn't look like this is ever going to get merged. @couchand, are you interested in maintaining a NuGet package for your fork?

**Comment by dharadharia** [comment]
I am also facing error, "	
'LongPollingTransport' does not contain a definition for 'AddHeaders' and no extension method 'AddHeaders' accepting a first argument of type 'LongPollingTransport' could be found (are you missing a using directive or an assembly reference?)"
Can someone please help to resolve it ASAP?

**Comment by couchand** [comment]
I'm cleaning out my queue.  It looks like this repo has been abandoned and this PR won't get merged.

@kjkrum I'm not interested in maintaining a NuGet package, but anyone who would like to is free to use this under the terms of the license of this repo.

**Pull request closed without merging**
